<?php

namespace AppBundle\Repository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{
    public function articulosDelPedido($id){
        return $this->createQueryBuilder('articulo')
            ->select('articulo.id', 'articulo.nombre', 'articulo.precio')
            ->leftJoin('articulo.pedido', 'pedido')
            ->andWhere('pedido.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute()
        ;
    }


    public function todosArticulosDelPedido($id)
    {
        return $this->articulosDelPedido($id)->execute();
    }
}
