<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function ClienteConPedidoMas30(){
        $query = $this->createQueryBuilder('cliente')
            ->select('cliente.nombre', 'pedidos.precio')
            ->leftJoin('cliente.pedidos', 'pedidos')
            ->andWhere('pedidos.precio > 30')
            ->getQuery()
            ->execute()
            ;
        return $query;
    }

    public function todosClienteConPedidoMas30(){
        return $this->ClienteConPedidoMas30()->execute();
    }


}

